---
# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

version: "3.9"

services:
  nginx:
    image: nginx
    ports:
      - "8200:80"
