# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  config.vm.box = 'ubuntu/hirsute64'

  # define manager nodes
  (1..3).each do |number|
    config.vm.define "m#{number}" do |node|
      node.vm.network 'private_network', ip: "192.168.99.20#{number}"
      node.vm.hostname = "m#{number}"
    end
  end

  # define worker nodes
  (1..4).each do |number|
    config.vm.define "w#{number}" do |node|
      node.vm.network 'private_network', ip: "192.168.99.21#{number}"
      node.vm.hostname = "w#{number}"
    end
  end

  # tweak vm settings to optimize for your machine:
  config.vm.provider 'virtualbox' do |vb|
    vb.memory = '4096'
    vb.cpus = 2
  end

  # install docker:
  config.vm.provision 'docker'

  # (optional) tools for demos:
  config.vm.provision 'shell', inline: <<-SHELL
    sudo apt-get install -y tree bat jq
    touch ~vagrant/.hushlogin
  SHELL
end

## NOTES
#
# ubuntu:
#   releases: https://wiki.ubuntu.com/Releases
#   official vagrant boxes: https://app.vagrantup.com/ubuntu/
#   suggested boxes (at time of recording):
#     21.04: https://app.vagrantup.com/ubuntu/boxes/hirsute64
#     20.04 (current LTS): ubuntu/focal64
#     22.04 (next LTS): ubuntu/jj # NOT OUT YET
#
# vagrant:
#   docs: https://docs.vagrantup.com.
#   box search: https://vagrantcloud.com/search.
#
# docker:
#   convenience install script: https://get.docker.com
#   linux (engine) install docs: https://docs.docker.com/engine/install/
#
