# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # hirsute64 is ubuntu 21.04, when the next LTS comes out I'd migrate to it (22.04 April 2022) or rollback to 20.04 (current LTS) if you have any trouble with hirsute64
  config.vm.box = "ubuntu/hirsute64"

  config.vm.provider "virtualbox" do |vb|
    # tweak vm settings to optimize for your machine:
    vb.memory = "4096"
    vb.cpus = 2
  end


  
end

## NOTES
# https://docs.vagrantup.com.
# boxes at https://vagrantcloud.com/search.
# - https://app.vagrantup.com/ubuntu/boxes/hirsute64
# - https://app.vagrantup.com/ubuntu/