# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  config.vm.box = 'ubuntu/hirsute64'

  # define manager nodes
  (1..3).each do |number|
    config.vm.define "m#{number}" do |node|
      node.vm.network 'private_network', ip: "192.168.99.20#{number}"
      node.vm.network 'forwarded_port', id: 'ssh', host: "820#{number}", guest: "22"
      node.vm.hostname = "m#{number}"
    end
  end
  
  # define worker nodes
  (1..4).each do |number|
    config.vm.define "w#{number}" do |node|
      node.vm.network 'private_network', ip: "192.168.99.21#{number}"
      node.vm.network 'forwarded_port', id: 'ssh', host: "821#{number}", guest: "22"
      node.vm.hostname = "w#{number}"
    end
  end
  
  # tweak vm settings to optimize for your machine:
  config.vm.provider 'virtualbox' do |vb|
    vb.memory = '4096'
    vb.cpus = 2
  end
  
  # install docker:
  config.vm.provision 'docker'
  
  # (optional) tools for demos:
  config.vm.provision 'shell', inline: <<-SHELL
    sudo apt-get install -y tree bat jq
    touch ~vagrant/.hushlogin
  SHELL
end
