---
version: "3.9"

services:
  web:
    image: weshigbee/swarmgs2-webstress
    ports:
      - "8400:3000/tcp"
    deploy:
      mode: global
    hostname: "stress-global-{{.Node.Hostname}}-{{.Task.Slot}}"
